.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -163,15 +163,70 @@ jobs:
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml   
   
+  smoke-test:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      # - run:
+      #     name: Install dependencies
+      #     command: |
+      #       # yum -y install python3
+      #       # yum -y install tar gzip
+      #       # yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
+      #       # yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1 -y
+      #       # yum install gcc-c++ make -y
+            
+            
+      # - run:
+      #     name: Get backend url
+      #     command: |
+      #       export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-server" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+      #       export API_URL="http://${BACKEND_IP}:3030"
+      # - run:
+      #     name: Backend smoke test.
+      #     command: |
+      #       export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-server" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+      #       export API_URL="http://${BACKEND_IP}:3030"
+      #       echo "${API_URL}"
+      #       if curl "${API_URL}/api/status" | grep "ok"
+      #       then
+      #         exit 0
+      #       else
+      #         exit 1
+            # fi
+      - run:
+          name: Get load balancer URL
+          command: |
+            LB_URL=$(aws elbv2 describe-load-balancers --query "LoadBalancers[0].DNSName" --output text)
+            echo "Load balancer URL: $LB_URL"
+            if curl -s ${LB_URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+          # command: |
+            
+          #   # URL="http://udapeople-"${CIRCLE_WORKFLOW_ID:0:7}".s3-website-us-east-1.amazonaws.com/#/employees"            
+          #   # echo ${URL} 
+          #   if curl -s ${URL} | grep "Welcome"
+          #   then
+          #     exit 0
+          #   else
+          #     exit 1
 
+      # Here's where you will add some code to rollback on failure  
+      # - revert-migrations
+      
 workflows:
   default:
     jobs:
-      - build-flutter
-      - deploy-infrastructure:
-          requires: [build-flutter]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]      
-      - deploy-flutter:
-          requires: [configure-infrastructure] 
+      # - build-flutter
+      # - deploy-infrastructure:
+      #     requires: [build-flutter]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]      
+      # - deploy-flutter:
+      #     requires: [configure-infrastructure] 
+      - smoke-test    
              
